import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Deploying IntegrityRegistry contract...");

  const IntegrityRegistry = await ethers.getContractFactory("IntegrityRegistry");
  const contract = await IntegrityRegistry.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log(`✅ IntegrityRegistry deployed to: ${address}`);

  // Write contract config for frontend
  const configDir = path.join(__dirname, "../../frontend/src/config");
  const configPath = path.join(configDir, "contract.ts");

  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  const configContent = `// Auto-generated by deploy script
export const CONTRACT_ADDRESS = "${address}";
export const CHAIN_ID = 31337;
`;

  fs.writeFileSync(configPath, configContent);
  console.log(`✅ Contract config written to: ${configPath}`);

  // Copy ABI to frontend
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/IntegrityRegistry.sol/IntegrityRegistry.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  
  const abiPath = path.join(configDir, "abi.ts");
  const abiContent = `// Auto-generated contract ABI
export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  
  fs.writeFileSync(abiPath, abiContent);
  console.log(`✅ Contract ABI written to: ${abiPath}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
