import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const networkName = network.name;
  const chainId = (network.config as { chainId?: number }).chainId ?? 31337;
  console.log(`Deploying IntegrityRegistry to ${networkName} (chain ${chainId})...`);

  const IntegrityRegistry = await ethers.getContractFactory("IntegrityRegistry");
  const contract = await IntegrityRegistry.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log(`✅ IntegrityRegistry deployed to: ${address}`);

  const configDir = path.join(__dirname, "../../frontend/src/config");
  const configPath = path.join(configDir, "contract.ts");

  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  // Keep the TypeScript fallback values up-to-date for local development
  const configContent = `// Contract configuration.
// In production (Vercel), set VITE_CONTRACT_ADDRESS and VITE_CHAIN_ID as
// environment variables in the Vercel project dashboard.
// For local development these values are auto-updated by \`npm run deploy\`.
export const CONTRACT_ADDRESS: string =
  import.meta.env.VITE_CONTRACT_ADDRESS ?? "${address}";

export const CHAIN_ID: number = Number(
  import.meta.env.VITE_CHAIN_ID ?? ${chainId}
);
`;

  fs.writeFileSync(configPath, configContent);
  console.log(`✅ Contract config written to: ${configPath}`);

  // Also write .env.local so Vite env vars take priority in the local dev server
  const envLocalPath = path.join(__dirname, "../../frontend/.env.local");
  const envContent = `# Auto-generated by deploy script – do not commit\nVITE_CONTRACT_ADDRESS=${address}\nVITE_CHAIN_ID=${chainId}\n`;
  fs.writeFileSync(envLocalPath, envContent);
  console.log(`✅ Frontend .env.local written: ${envLocalPath}`);

  if (networkName === "sepolia") {
    console.log(`\n📋 Next steps:`);
    console.log(`   Set these in your Vercel project → Settings → Environment Variables:`);
    console.log(`   VITE_CONTRACT_ADDRESS=${address}`);
    console.log(`   VITE_CHAIN_ID=${chainId}`);
  }

  // Copy ABI to frontend
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/IntegrityRegistry.sol/IntegrityRegistry.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  
  const abiPath = path.join(configDir, "abi.ts");
  const abiContent = `// Auto-generated contract ABI
export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  
  fs.writeFileSync(abiPath, abiContent);
  console.log(`✅ Contract ABI written to: ${abiPath}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
